### PR TITLE
Add shirosaki email address

### PR DESCRIPTION
**Pull request by shirosaki**

### CODE REVIEW

**Comment by shirosaki** [comment]
@hsbt Thank you.
But I still fails on push.

`ssh git@git.ruby-lang.org` is OK with my ssh key.

```
$ git push upstream master
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 12 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 863 bytes | 863.00 KiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Your ssh key is unknown.
remote: Please see https://github.com/ruby/ruby-commit-hook/blob/master/config/email.yml
remote: and send PR, or contact on ruby-core@ruby-lang.org.
To git.ruby-lang.org:ruby.git
 ! [remote rejected]       master -> master (pre-receive hook declined)
error: failed to push some refs to 'git.ruby-lang.org:ruby.git'
```

**Comment by hsbt** [comment]
@shirosaki Thanks for reporting. This configuration is not applied yet. It's affected with server migration. 

I'm working to investigate it.

**Comment by hsbt** [comment]
@shirosaki I update this configuration on git.ruby-lang.org. Can you try again?

**Comment by shirosaki** [comment]
@hsbt Thanks. It worked!

**Pull request merged**
